module:
  Options:
    Interval: 100
network:
  Endian: false
  IsJson: false
  LenMsgLen: 2
  MinMsgLen: 1
  MaxMsgLen: 4096
  Services:
    - Area: 1
      Type: 1
      ID: 1
      Name: TcpService
      Protocol: tcp
      Ip: 127.0.0.1
      Port: 8888
      Linger: 0
      KeepAlive: true
      KeepAlivePeriod: 0
      ReadBufferSize: 0
      WriteBufferSize: 0
      ReadTimeout: 0
      WriteTimeout: 0
# github.com/arl/statsviz
statsviz:
  IsOpen: true # 是否开启
  Addr: ':6060' # 地址
